// Generated by Selenium IDE

using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;

namespace PerformanceTestingPOV;

public class SuiteTests : IDisposable
{
    public IWebDriver Driver { get; private set; }
    public IDictionary<String, Object> Vars { get; private set; }
    public IJavaScriptExecutor Js { get; private set; }
        
    private TestInfo _testInfo;
    
    public SuiteTests()
    {
        Driver = new ChromeDriver();
        Js = (IJavaScriptExecutor)Driver;
        Vars = new Dictionary<String, Object>();

        var testSiteSetup = TestSiteSetup.GetTestInfo(TestSitesEnum.DemoEvergreenLocal)
            .ConfirmTestInfoPopulated()
            .SetQueryStoreOn()
            .WarmUpSite(WarmUpAction, Driver)
            .SetQueryStoreClear()
            .SetViewQueryStoreMostExpensiveQueries()
            .SetViewQueryStoreMostFrequentQueries();
        
        _testInfo = testSiteSetup.GetTestInfo();
        
        AddSomeProductsToCart();
        
        // Get the query store info
        testSiteSetup.GetQueryStoreMostExpensiveQueries()
            .GetQueryStoreMostFrequentQueries();
    }
    
    public void Dispose()
    {
        Driver.Quit();
    }

    [Fact]
    public void RunMyTest()
    {
        Assert.True(true);
    }


    private readonly Action<IWebDriver, string> WarmUpAction = (driver, url) =>
    {
        driver.Navigate().GoToUrl(url);
        var wait = new OpenQA.Selenium.Support.UI.WebDriverWait(driver, TimeSpan.FromSeconds(30));
        wait.Until(d => d.FindElements(OpenQA.Selenium.By.CssSelector(".widget-logo.main-logo")).Count > 0);
    };
    
    public void AddSomeProductsToCart()
    {
        var baseUrl = _testInfo.Url;
        Driver.Navigate().GoToUrl($"{baseUrl}");
        Driver.Manage().Window.Size = new System.Drawing.Size(1720, 1099);
        Driver.Navigate().GoToUrl($"{baseUrl}/sports-and-outdoors-sx01/fitness-sx0101/exercise-machines-sx010101");
        Driver.FindElement(By.CssSelector(".product:nth-child(1) .widget-productlist-atc-button")).Click();
        Driver.FindElement(By.CssSelector(".product:nth-child(2) .widget-productlist-atc-button")).Click();
        {
            var element = Driver.FindElement(By.CssSelector(".container > ul > li:nth-child(2) span"));
            Actions builder = new Actions(Driver);
            builder.MoveToElement(element).Perform();
        }
        Driver.Navigate().GoToUrl($"{baseUrl}/office-products-sx03/writing-sx0301/gel-pens-sx030102");
        Driver.FindElement(By.CssSelector(".product:nth-child(1) .widget-productlist-atc-button")).Click();
        Driver.FindElement(By.CssSelector("li:nth-child(1) > .ico-heading > span")).Click();
        Driver.FindElement(By.CssSelector("li:nth-child(2) > .ico-heading > span")).Click();
        Driver.Navigate().GoToUrl($"{baseUrl}/banners");
        {
            var element = Driver.FindElement(By.CssSelector(".container > ul > li:nth-child(2) span"));
            Actions builder = new Actions(Driver);
            builder.MoveToElement(element).Perform();
        }
        Driver.Navigate().GoToUrl($"{baseUrl}/office-furniture-sx05/chairs-sx0501/visitor-chairs-sx050103");

        Driver.Navigate().GoToUrl($"{baseUrl}/cart");
        var alertButton = By.CssSelector(".notification-actions > .btn");
        if (Driver.FindElements(alertButton).Count > 0)
        {
            Driver.FindElement(alertButton).Click();
        }

        var searchBox = Driver.FindElement(By.CssSelector("[id^='product-search-autocomplete-']"));
        searchBox.Click();
        searchBox.SendKeys("Tennis");
        {
            WebDriverWait wait = new WebDriverWait(Driver, System.TimeSpan.FromSeconds(3));
            wait.Until(driver => driver.FindElements(By.LinkText("Champion Sports 3.6mm Tennis Net")).Count > 0);
        }
        searchBox.Clear();
        searchBox.SendKeys("Office");
        {
            WebDriverWait wait = new WebDriverWait(Driver, System.TimeSpan.FromSeconds(3));
            wait.Until(driver => driver.FindElements(By.LinkText("Office Star Fabric Visitor's Chair - Mesh Back")).Count > 0);
        }
        Driver.Navigate().GoToUrl($"{baseUrl}/champion-sports-3-6mm-tennis-net-cv119");
        Driver.FindElement(By.CssSelector(".cv-add-to-cart")).Click();
    }
}